---
title: "Data Generation Mechanisms"
author: "Judith Neve"
date: '2022-10-31'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pmsampsize) # sample size calculations
library(tidyr)      # pivot, pipes
library(MASS)       # mvrnorm
library(dplyr)      # data wrangling
library(pROC)       # AUC
```

# Aim

Identify the best combination of hyperparameters for which tuning leads to the best predictive performance of a prediction model.

# DGM

## Population

```{r}
# factors we vary in population factors: number of predictors, event fraction, sample size
p  <- c(8, 16)
EF <- c(0.1, 0.3, 0.5)
N  <- c(0.5, 1)
```

```{r}
source("DGMFunctions.R")
source("DataSimFunctions.R")
```

```{r}
set.seed(0070661)
scenarios <- make_scenarios(n_pred = p, event_fraction = EF, sample_size = N)
save(scenarios, file = "DGM_data/scenarios.RData")
set.seed(NULL)
```

## True effect estimation

```{r}
start_seed <- 100
set.seed(start_seed)
example_n <- 1e5
n_beta_repetitions <- 20

start_beta_est <- Sys.time()
betas_matrices <- gen_multiple_betas(
  n_predictors = p, prevalences = EF, n_beta_repetitions = n_beta_repetitions,
  example_n = example_n, start_seed = start_seed
)
end_beta_est <- Sys.time()

set.seed(2 * start_seed)
beta_validation <- lapply(betas_matrices, validate_betas, example_n = example_n, n_predictors = p, prevalences = EF)

beta_valid_df <- do.call(rbind, beta_validation)  %>%
  as.data.frame() %>% 
  mutate(iteration = rep(1:n_beta_repetitions, each = 6),
         prev_diff = abs(`validation prevalence` - prevalence),
         AUC_noint_diff = abs(`validation AUC (no interaction)` - 0.7),
         AUC_diff = abs(`validation AUC (interaction)` - 0.8))

betas_matrix <- beta_valid_df %>% 
  mutate(abs_diff = prev_diff + AUC_noint_diff + AUC_diff) %>% 
  group_by(n_predictor, prevalence) %>% 
  filter(abs_diff == min(abs_diff)) %>% 
  select(n_predictor:gamma) %>%
  arrange(n_predictor, prevalence) %>%
  as.matrix()

save(betas_matrix, file = "DGM_data/betas.RData")
```


```{r}
set.seed(3 * start_seed)
validation_betas_matrix <- validate_betas(
 betas_matrix = betas_matrix, example_n = example_n, n_predictors = p, prevalences = EF
)

cat("\nMax. (no interaction) AUC dev from 0.7:", max(abs(validation_betas_matrix[,6] - 0.7)))
cat("\nMax. AUC dev from 0.8:", max(abs(validation_betas_matrix[,7] - 0.8)))
cat("\nMax. dev from prevalence:", max(abs(validation_betas_matrix[,8] - c(rep(c(0.1, 0.3, 0.5), 2)))))
cat("\nMax. difference between total main effects and total interaction effects: ", abs(abs(betas_matrix[,1]*betas_matrix[,4]) - abs(betas_matrix[,1]*betas_matrix[,5]/4)) %>% max())
```


```{r}
set.seed(4*start_seed)
beta_estimations <- recover_betas(betas_matrix)

save(beta_estimations, validation_betas_matrix, file = "DGM_data/betas_validation.RData")
```

# Estimands

Predictive performance and computational time.

# Session info

```{r}
writeLines(capture.output(sessionInfo()), "DGM_scenarios_betas_sessionInfo.txt")
```


