---
title: "Data Generation Scenarios"
author: "Judith Neve"
date: '2022-10-31'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(pmsampsize)
library(tidyr)
```

We will generate data under a logistic regression model with strong interactions.

Vary:
* number of predictors
* event fraction
* sample size

```{r}
n_pred         <- c(8, 16, 32)
event_fraction <- c(0.1, 0.3, 0.5)
```

Minimum sample size calculation based on Riley et al., 2020

```{r}
req_n <- data.frame(
  n_pred         = rep(n_pred,         each  = length(event_fraction)),
  event_fraction = rep(event_fraction, times = length(n_pred)),
  req_n          = rep(NA, length(n_pred)*length(event_fraction))
  )

for (p in n_pred) {
  for (ef in event_fraction) {
    req_n$req_n[(req_n$n_pred) == p & (req_n$event_fraction == ef)] <- pmsampsize(
      type = "b",
      parameters = p,
      prevalence = ef,
      cstatistic = 0.8                 # TODO: what's realistic??
      )$sample_size
  }
}
```

Manipulate the sample sizes.

```{r}
sample_size <- c(0.5, 1, 2)

n_cols <- matrix(
  NA,
  nrow = nrow(req_n),
  ncol = length(sample_size)
) %>%
  as.data.frame()

colnames(n_cols) <- sample_size

for (j in 1:length(sample_size)) {
  n_cols[,j] <- req_n$req_n * sample_size[j]
}
```

Combine the info into one table to have one row per scenario

```{r}
scenarios <- cbind(req_n[,-3], n_cols) %>%
  pivot_longer(
    `0.5`:`2`,
    names_to = "prop_min_n",
    values_to = "n"
    )
```

```{r}
write.csv(scenarios, file = "DataScenarios.csv", row.names = FALSE)
```

