---
title: "Sensitivity analyses"
author: "Judith Neve"
date: '2023-01-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
```

# min.node.size

```{r mns sens data}
load("Data/select_minnodesize.RData")
```

```{r}
select_min.node.size %>% 
  group_by(dataset_id) %>% 
  mutate(best_min.node.size = (min(deviance) == deviance),
         prop_min.node.size = min.node.size / (n)) %>% 
  filter(best_min.node.size) %>% 
  filter(min.node.size == min(min.node.size)) %>% 
  group_by(p, EF, n) %>% 
  mutate(med  = median(min.node.size),
         mean = mean(min.node.size)) %>% 
  ggplot(aes(x = min.node.size, fill = factor(n))) +
  geom_histogram(binwidth = 1) +
  facet_wrap(~ p + EF,
             scales = "free_x") +
  geom_vline(xintercept = 10, linewidth = 1.2) +
  # geom_vline(aes(xintercept = n*EF*0.25), linewidth = 1.2, col = "pink") +
  # geom_vline(aes(xintercept = med), col = "blue") +
  # geom_vline(aes(xintercept = mean), col = "red") +
  theme_classic()
```


# sample.fraction

```{r}
load("Data/select_samplefrac.RData")
# load("Data/select_samplefrac2.RData")
# select_sample.frac2 <- select_sample.frac2 %>% 
#   mutate(dataset_id = paste0(select_sample.frac2$dataset_id, "_2"))
# select_sample.frac <- select_sample.frac %>% 
#   rbind(select_sample.frac2)
# rm(select_sample.frac2)
```

```{r}
per_20 <- select_sample.frac %>% 
  filter(sample.fraction %in% seq(0.2, 1, by = 0.2)) %>% 
  group_by(dataset_id) %>% 
  filter(min(deviance, na.rm = TRUE) == deviance) %>% 
  filter(sample.fraction == min(sample.fraction))

per_10 <- select_sample.frac %>% 
  filter(sample.fraction %in% seq(0.1, 1, by = 0.1)) %>% 
  group_by(dataset_id) %>% 
  filter(min(deviance, na.rm = TRUE) == deviance) %>% 
  filter(sample.fraction == min(sample.fraction))

per_5 <- select_sample.frac %>% 
  filter(sample.fraction %in% seq(0.05, 1, by = 0.05)) %>% 
  group_by(dataset_id) %>% 
  filter(min(deviance, na.rm = TRUE) == deviance) %>% 
  filter(sample.fraction == min(sample.fraction))

per_1 <- select_sample.frac %>% 
  group_by(dataset_id) %>% 
  filter(min(deviance, na.rm = TRUE) == deviance) %>% 
  filter(sample.fraction == min(sample.fraction))

compare <- data.frame(
  dataset_id = per_1$dataset_id,
  sample.fraction_1 = per_1$sample.fraction,
  deviance_1 = per_1$deviance,
  sample.fraction_5 = per_5$sample.fraction,
  deviance_5 = per_5$deviance,
  sample.fraction_10 = per_10$sample.fraction,
  deviance_10 = per_10$deviance,
  sample.fraction_20 = per_20$sample.fraction,
  deviance_20 = per_20$deviance
)
```

```{r}
load("Data/scenarios.RData")
compare_long <- compare %>%
  mutate(p = rep(scenarios$n_pred, each = 25),
         EF = rep(scenarios$event_fraction, each = 25),
         n = rep(scenarios$n, each = 25),
         scenario = rep(1:12, each = 25)) %>% 
  pivot_longer(cols = c("sample.fraction_1", "sample.fraction_5", "sample.fraction_10", "sample.fraction_20"), names_to = "step", values_to = "sample.fraction") %>%
  mutate(deviance = ifelse(step == "sample.fraction_1", deviance_1,
                           ifelse(step == "sample.fraction_5", deviance_5,
                                  ifelse(step == "sample.fraction_10", deviance_10,
                                         deviance_20)))) %>% 
  dplyr::select(-deviance_1, -deviance_5, -deviance_10, -deviance_20) %>% 
  mutate(step = recode(step,
                       "sample.fraction_1" = 1,
                       "sample.fraction_5" = 5,
                       "sample.fraction_10" = 10,
                       "sample.fraction_20" = 20))
head(compare_long)
```

```{r}
set.seed(1559)
compare_long %>% 
  ggplot(aes(x = factor(step), y = deviance)) +
  geom_violin() +
  geom_boxplot() +
  geom_line(data = compare_long %>%
              filter(dataset_id %in% sample(compare$dataset_id, 120)),
            mapping = aes(group = dataset_id)) +
  facet_wrap(~ factor(scenario), scales = "free")
```


```{r}
select_sample.frac %>% 
  group_by(dataset_id) %>% 
  filter(min(deviance, na.rm = TRUE) == deviance) %>% 
  filter(sample.fraction == min(sample.fraction)) %>% 
  group_by(p, EF, n) %>% 
  # mutate(med  = median(min.node.size),
  #        mean = mean(min.node.size)) %>% 
  ggplot(aes(x = sample.fraction, fill = factor(n))) +
  geom_histogram() +
  facet_wrap(~ p + EF,
             scales = "free_x") +
  theme_classic()
```

