---
title: "Testing beta generation"
author: "Judith Neve"
date: '2023-01-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pmsampsize)
library(tidyr)
library(MASS)
library(dplyr)
library(pROC)
set.seed(0070661)
```

## Population

```{r}
p  <- c(8, 16)
EF <- c(0.1, 0.3, 0.5)
N  <- c(0.5, 1) # scrapped x2
```

```{r}
source("DataSimFunctions.R")
```

```{r}
# scenarios <- make_scenarios(n_pred = p, event_fraction = EF, sample_size = N)
# save(scenarios, file = "scenarios.RData")
load("Data/scenarios.RData")

# n_datasets <- 1000
n_datasets <- 10
```

## True effect estimation

```{r}
source("GenerateBetas.R")
```

```{r}
start_seed <- 100
example_n <- 1e5
n_beta_repetitions <- 20

# b1 <- generate_betas(example_n = example_n, n_predictors = p, prevalences = EF, initial_betas = initial_betas)
# b2 <- generate_betas(example_n = example_n, n_predictors = p, prevalences = EF, initial_betas = initial_betas)

betas_matrix <- mean_multiple_betas(
  n_predictors = p, prevalences = EF, n_beta_repetitions = n_beta_repetitions,
  example_n = example_n, start_seed = start_seed
)

betas_matrix[[1]]

set.seed(2 * start_seed)
validation_betas_matrix <- validate_betas(
 betas_matrix = betas_matrix[[1]], example_n = example_n, n_predictors = p, prevalences = EF
)

ind_validation <- lapply(betas_matrix[[2]], validate_betas, example_n = example_n, n_predictors = p, prevalences = EF)

ind_valid_df <- do.call(rbind, ind_validation) %>%
  as.data.frame() %>% 
  mutate(prev_diff = abs(`validation prevalence` - prevalence))

save.image(file = "inspectbetas.RData")
# save(betas_matrix[[1]], file = "full_sum_20_it.RData")
```

```{r}
load("betas_v2.RData")
#
set.seed(2 * start_seed)
validation_betas_matrix <- validate_betas(
 betas_matrix = betas_matrix, example_n = example_n, n_predictors = p, prevalences = EF
)
validation_betas_matrix <- cbind(validation_betas_matrix,
  c("BAD (all)", "", "BAD (AUC)", "", "BAD (all)", "")
)
# 
# save(betas_matrix, file = "betas_v2.RData")

# TODO: fix beta generation
# TODO: fix beta validation
```

```{r}
# iteration 10
betas_matrix10 <- matrix(c(
        8 ,       0.1, -2.6325908,  0.27466521 ,-0.7677037,
        8 ,       0.3, -1.3555393,  0.20298309  ,0.7973221,
        8 ,       0.5, -0.2205444,  0.24363288  ,0.8701202,
       16,        0.1, -3.0418649,  0.07586594  ,0.4390843,
       16,        0.3, -1.4480226, -0.10949682,  0.5080349,
       16,        0.5, -0.2936688, -0.13668179,  0.5539992), nrow = 6, byrow = TRUE)

# iteration 1
betas_matrix <- matrix(c(
      8 ,       0.1, -1.518435541,  0.3160109 ,-1.3562379,
      8 ,       0.3, -1.365616337,  0.2010274 , 0.7344432,
      8 ,       0.5, -0.006520841,  0.2453328 , 0.1220903,
     16,        0.1, -2.558958399, -0.1562143, -0.5391441,
     16,        0.3, -0.352863774,  0.1638646 ,-0.7891204,
     16,        0.5, -0.264725214,  0.1447085 , 0.5964248), nrow = 6, byrow = TRUE)

# iteration 2
betas_matrix <- matrix(c(
      8 ,       0.1, -2.6071965  ,0.26798685 ,-0.7685643,
      8 ,       0.3, -1.3463359  ,0.20805357  ,0.7904513,
      8 ,       0.5, -0.3808939  ,0.26079684  ,0.9233774,
     16,        0.1, -2.8622608  ,0.09508705  ,0.7898814,
     16,        0.3, -0.8473190, -0.15108538 -0.5582226,
     16,        0.5,  0.3229791  ,0.13678350 ,-0.5602170), nrow = 6, byrow = TRUE)

# iteration 3
betas_matrix3 <- matrix(c(
      8 ,       0.1, -2.6361955,  0.2718955 ,-0.7734865,
      8 ,       0.3, -1.3586099,  0.2101654 , 0.8029827,
      8 ,       0.5, -0.2127545,  0.2458448 , 0.8407041,
     16,        0.1, -2.5385002,  0.1554612 ,-0.5144769,
     16,        0.3, -1.5839379, -0.1023035,  0.4645255,
     16,        0.5,  0.3149505 ,-0.1341466 ,-0.5495988), nrow = 6, byrow = TRUE)

# iteration 5
betas_matrix5 <- matrix(c(
     8        ,0.1 ,-2.61933858,  0.2702592, -0.7899276,
     8        ,0.3 ,-1.35323688,  0.2067276,  0.7986572,
     8        ,0.5 ,-0.21036121,  0.2492922,  0.8486669,
    16        ,0.1 ,-2.51704801,  0.1016668,  0.1983231,
    16        ,0.3 ,-1.47298904, -0.1129015,  0.5164381,
    16        ,0.5 , 0.09646004,  0.2453774, -1.3563437), nrow = 6, byrow = TRUE)

# iteration 7
betas_matrix7 <- matrix(c(
       8      ,  0.1, -2.6267797,  0.27294370, -0.7822742,
       8      ,  0.3, -1.3602365,  0.20241817,  0.7894059,
       8      ,  0.5, -0.2149655,  0.24434160,  0.8428526,
    16        ,0.1 ,-3.0238459 ,-0.07480896,  0.4273111,
    16        ,0.3 ,-1.3927201 ,-0.11077720,  0.3819729,
    16        ,0.5 ,-0.2938300 ,-0.13575380,  0.5658436), nrow = 6, byrow = TRUE)

betas_matrix <- (betas_matrix10 + betas_matrix3 + betas_matrix5 + betas_matrix7)/4

set.seed(200)
validation_betas_matrix <- validate_betas(
 betas_matrix = betas_matrix, example_n = example_n, n_predictors = p, prevalences = EF
)
```


