---
title: "Data Generation"
author: "Judith Neve"
date: '2022-10-31'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(pmsampsize)
library(tidyr)
library(MASS)
library(dplyr)
```

```{r}
source("DataSimFunctions.R")
```

```{r}
n_pred         <- c(8, 16, 32)
event_fraction <- c(0.1, 0.3, 0.5)
sample_size    <- c(0.5, 1, 2)
```

```{r}
scenarios <- make_scenarios(n_pred, event_fraction, sample_size)
scenarios_red <- scenarios %>% filter(n_pred == 8, event_fraction == 0.1)
dat <- sim_data(scenarios_red, 10) # 1000 reps: 7GB - if stored as a list, 4GB
```

Now I want to do some tuning for each of these datasets

use caret (grid search), optimise accuracy, fit a random forest (and CV) for each dataset, on each dataset tune according to all the relevant combinations

```{r}
toy_dat <- dat[dat[,"dataset_id"] == "1_1",] %>%
  as.data.frame() %>% 
  pivot_wider(names_from = Pred_number, values_from = Pred_value)

toy_dat[c(1, 7:14)]  <- lapply(toy_dat[c(1, 7:14)], as.numeric)
```

```{r}
mod <- glm(Y ~ .*., data = toy_dat %>% select(-c(id, sample_size_prop, n_pred, event_fraction, dataset_id)), family = binomial())

summary(mod)
```


```{r}
toy_dat <- dat[[i]][[j]]
```

```{r}
library(caret)
```

```{r}
set.seed(1)
# TODO: find how to make a full grid for ALL the hyperparameters I want
# TODO: have relevant values for the hyperparameters

defaults <- c(
  num.trees                 = 500,
  replace                   = TRUE,
  sample.fraction           = ifelse(replace, 1, 0.632),
  mtry                      = floor(sqrt(p)),
  respect.unordered.factors = "ignore", # but if splitrule = extratrees, this is "partition". "order" is also an option
  min.node.size             = 1,
  splitrule                 = "gini" # other options are extratrees and hellinger
  )


tuneGrid <- expand.grid(
  mtry = c(1:3),                                      # TODO: this goes to n_pred
  splitrule = c("gini", "extratrees", "hellinger"),
  min.node.size = c(1:5)                              # TODO: what's the biggest node size? n?
  )
ctrl <- trainControl(
  method = "cv",
  number = 5
)
# TODO: set the folds rather than have them be done within train

model1 <- train(
  x = toy_dat[,1:32],
  y = as.factor(toy_dat[,"Y"]),
  method = "ranger",
  trControl = ctrl,
  tuneGrid = tuneGrid,
  # hyperparameters not tuned by caret
  num.trees = 1,                        # change this to i and loop over doing this for many trees?
  replace = TRUE,                       # same code, replace = FALSE
  sample.fraction = 1,                  # same code, loop?
  respect.unordered.factors = "ignore"  # change this
)
model1
# TODO: how to extract results for best tune
```

